### ISSUE TITLE
atan2 in std

### ISSUE THREAD

**Issue by sciconf** [CertainLach/jrsonnet#141]
It would be great to add atan2 to std.  atan2 is super useful for converting from rectangular to polar coordinates.

I think it looks something like this, but ... I'm not expert with rust at all:
```
--- a/crates/jrsonnet-stdlib/src/lib.rs
+++ b/crates/jrsonnet-stdlib/src/lib.rs
@@ -104,6 +104,7 @@ pub fn stdlib_uncached(settings: Rc<RefCell<Settings>>) -> ObjValue {
                ("asin", builtin_asin::INST),
                ("acos", builtin_acos::INST),
                ("atan", builtin_atan::INST),
+               ("atan2", builtin_atan2::INST),
--- a/crates/jrsonnet-stdlib/src/math.rs
+++ b/crates/jrsonnet-stdlib/src/math.rs
@@ -89,6 +89,11 @@ pub fn builtin_atan(x: f64) -> f64 {
        x.atan()
 }

+#[builtin]
+pub fn builtin_atan2(y:f64, x: f64) -> f64 {
+       y.atan2(x)
+}
+

```

**Comment by CertainLach** [comment]
I agree this is useful, and yes, your code is correct for that.
I have such helper in one of my projects using jsonnet for now:
```jsonnet
local atan2(y, x) =
  if x > 0 then
    atan(y / x)
  else if x < 0 && y >= 0 then
    atan(y / x) + pi
  else if x < 0 && y < 0 then
    atan(y / x) - pi
  else if x == 0 && y > 0 then
    pi / 2
  else if x == 0 && y < 0 then
    -pi / 2
  else
    error "undefined"; 
```

But I agree this is acceptable to add this to standard library. The problem is, it should also be added to official jsonnet implementation...

**Comment by sciconf** [comment]
I also have nearly the same jsonnet atan2 code myself too, but it just seems better to be in std with all the other trig.  I put a request in for the c++ library as well:
https://github.com/google/jsonnet/issues/1118
But, since jrsonnet is way faster and what I actually use, this is where I'd really like it :).
