### ISSUE TITLE
Break the loop in jsonnet 

### ISSUE THREAD

**Issue by redoC-A2k** [CertainLach/jrsonnet#161]
I want to break loop ( it can be through std.map function or for loop)  in jsonnet ? Isn't there any keyword or functionality like "break" keyword in jsonnet similar to conventional loops .
If not is it possible to modify source code of jrsonnet so as to have similar functionality ?

**Comment by CertainLach** [comment]
Jsonnet is functional, and break is not something that makes sense here

Instead you're supposed to write code over combinators, where everything lazy and not reachable will be just not executed.

```jsonnet
local takeUntil(arr, until) = std.foldl(
   function(acc,i) if acc.finished then acc else acc {out+: [i], finished: i == until},
   arr,
   {out: [], finished: false}
).out;

local mapped = std.map(function(a) a * 2, [1, 2, 3, 4, 5, 6, error "will not reach this element"]);
takeUntil(mapped, 6) == [2, 4, 6]
```

**Comment by redoC-A2k** [comment]
Thanks a lot for letting me know about std.foldl using that function we achived what we wanted to do .
