### ISSUE TITLE
WASM/Rust for stdlib Native Extensions?

### ISSUE THREAD

**Issue by rrichardson** [CertainLach/jrsonnet#22]
Is there a way, or could there easily be a way to extend the stdlib using WASM and/or Rust?

**Comment by CertainLach** [comment]
Yep, it is available via api: https://github.com/CertainLach/jrsonnet/blob/ce2d8d503b4aa249b441db4055e295fa158616e7/crates/jrsonnet-evaluator/src/lib.rs#L431

But no such functionality for standard CLI. I can implement it, but i dont think it will be useful. Vanilla jsonnet also doesn't supports it (But there is existing issue: https://github.com/google/jsonnet/issues/206)
