### ISSUE TITLE
Possible syntax validation error?

### ISSUE THREAD

**Issue by radioegor146** [CertainLach/jrsonnet#25]
When tried to compile that jsonnet:
```
let a = 1;
```
I've got just "syntax error" in output in any mode.
Using jrsonnet 0.3.1.

**Comment by CertainLach** [comment]
This is not an error, you will get same result with C++/Golang impl of jsonnet

`let` statements are invalid themselves, full syntax for them is
`let VAR = VALUE; RESULT`
Where second expression runs in scope with specified VAR, and you are missing it.

**Comment by CertainLach** [comment]
Oh, and there is no `let`s in jsonnet, you meant `local`

**Comment by CertainLach** [comment]
Oh, and there is a regression in jrsonnet cli: #26

**Comment by radioegor146** [comment]
That's an issue about the output of error messages, not the language itself.
