### ISSUE TITLE
Differences in output compared to c-jsonnet

### ISSUE THREAD

**Issue by akursell-wish** [CertainLach/jrsonnet#32]
I am trying to migrate a very large jsonnet repo to use `jrsonnet`, and I have noticed the following differences in output from the same source as compared to the C implementation:

- Empty arrays and objects do not contain a space between the brackets:
```bash
$ echo '[{}, []]' | jsonnet -
[
   { },
   [ ]
]
$ echo '[{}, []]' | jrsonnet -
[
   {},
   []
]
```

- `std.range(from, to)` produces different output when `to < from`:
```bash
$ echo '[x for x in std.range(0, -3)]' | jsonnet -
[ ]
$ echo '[x for x in std.range(0, -3)]' | jrsonnet -
[
   0
]
```
It could be argued that calling range with `to < from` is UB, but outputting no elements in this case seems more correct than always outputting 1.

- `jrsonnet` adds a newline when outputting zero items in a `--yaml-stream`:
```bash
$ echo '[]' | jsonnet -y -
$ echo '[]' | jrsonnet -y -

$
```

I'm not sure to what degree you are aiming for output compatibility with `jsonnet` and `go-jsonnet`, but if you are, these are the only differences I've found.

**Comment by CertainLach** [comment]
> Empty arrays and objects do not contain a space between the brackets:

Jsonnet itself isn't consistent in inserting spaces between brackets, for example, https://jsonnet.org/ doesn't handles it this way too, not sure about go impl.

Probally i should leave those kind of issue as wontfix, but i will check go impl handling first.

Two other issues should be fixed, yeah.

**Comment by akursell-wish** [comment]
Just checked the golang version. It adds the space as well:
```
$ echo '[{}, []]' | ./jsonnet -
[
   { },
   [ ]
]
```

**Comment by CertainLach** [comment]
Well, fixed by https://github.com/CertainLach/jrsonnet/commit/847c11f5901f4c67125101caabc2c34d1d31bf91 https://github.com/CertainLach/jrsonnet/commit/6341ead30a0b0f9a1fc90e53074249f7d67007c3 https://github.com/CertainLach/jrsonnet/commit/a90b3d609f9a93f2ccf1b937a1e7ab55bdcdea7f
