### ISSUE TITLE
code for benchmarks (large_string_join, etc.)

### ISSUE THREAD

**Issue by moleike** [CertainLach/jrsonnet#37]
Hi there, 
I am looking to use your bench suite [here](https://gist.github.com/CertainLach/5770d7ad4836066f8e0bd91e823e451b), to run it against a [different](https://github.com/moleike/haskell-jsonnet) Jsonnet implementation not covered in your comparison. would you mind sharing the code for the first 4 benchmarks? `large_string_join`, `large_string_template`, `realistic1`, `realistic2`

Thanks!

**Comment by CertainLach** [comment]
Benchmarks .md file is generated by this .nix flake (You can add your jsonnet implementation to it):
https://gist.github.com/CertainLach/5770d7ad4836066f8e0bd91e823e451b#file-flake-nix

Benchmarks you mentioned are ran from `perf_tests` directory of jsonnet repo

**Comment by moleike** [comment]
Got it, I will update the .nix flake soon when I can look into it, thanks!
