### ISSUE TITLE
Assert support

### ISSUE THREAD

**Issue by vincent-herlemont** [CertainLach/jrsonnet#40]
Is assert support are implemented?

I test with the following code, usually is must trows an error:
```jsonnet
local conf = {
    n: ""
};

conf + {
    assert std.isNumber(self.n)
}
```
Official output throw an error:
```
./test.jsonnet CLOSE_WRITE,CLOSE
RUNTIME ERROR: Object assertion failed.
	./test.jsonnet:6:12-32	thunk <object_assert>
	During manifestation	
```
With the crate `jrsonnet-evaluator:0.3.6` output do not throw an error:
```json
{"n": ""}
```

Below source code that I use:
```rust
use jrsonnet_evaluator::error::LocError;
use jrsonnet_evaluator::{EvaluationState, FileImportResolver};
...
let mut vm = EvaluationState::default();

vm.with_stdlib();

vm.set_import_resolver(Box::new(FileImportResolver {
    library_paths: vec![current_dir().unwrap()],
}));

let val = vm.evaluate_file_raw(&file.to_path_buf())?;

let val = vm.with_tla(val)?;

let output = vm.manifest(val).to_string();
```
Do I miss some things?

I see a `TODO: Assert` in the code of  `jrsonnet-evaluator` is it link to this feature?
https://github.com/CertainLach/jrsonnet/blob/5ee9e00075c90f5fa72cc6a9d765e950c48df7c4/crates/jrsonnet-evaluator/src/evaluate.rs#L310

**Comment by CertainLach** [comment]
It was fixed in https://github.com/CertainLach/jrsonnet/commit/1cc9e6c67fda282755d18762335e8bb74692a618
