### ISSUE TITLE
panicking on file input

### ISSUE THREAD

**Issue by cloudcalvin** [CertainLach/jrsonnet#46]
When using jrsonnet version 3.7 (both linux versions) I get the following error:

> jrsonnet  testing.jsonnet
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/jrsonnet-cli/src/lib.rs:48:16
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

With backtrace :

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/jrsonnet-cli/src/lib.rs:48:16
> stack backtrace:
>    0:     0x5574508f5e50 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
>    1:     0x5574508f5e50 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
>    2:     0x5574508f5e50 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/sys_common/backtrace.rs:67:5
>    3:     0x5574508f5e50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/sys_common/backtrace.rs:46:22
>    4:     0x55745091691c - core::fmt::write::h7aa6cd0067dca82a
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/fmt/mod.rs:1110:17
>    5:     0x5574508f3a15 - std::io::Write::write_fmt::heb07fc0616bbd06d
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/io/mod.rs:1588:15
>    6:     0x5574508f7eab - std::sys_common::backtrace::_print::h2c2441c37e894fb5
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/sys_common/backtrace.rs:49:5
>    7:     0x5574508f7eab - std::sys_common::backtrace::print::h4fb679ac439362ea
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/sys_common/backtrace.rs:36:9
>    8:     0x5574508f7eab - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:208:50
>    9:     0x5574508f7981 - std::panicking::default_hook::hb25822b45f6fdc4e
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:225:9
>   10:     0x5574508f8551 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:622:17
>   11:     0x5574508f8027 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:517:13
>   12:     0x5574508f632c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/sys_common/backtrace.rs:141:18
>   13:     0x5574508f7fb9 - rust_begin_unwind
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:515:5
>   14:     0x55745051c3c1 - core::panicking::panic_fmt::hbe99dddd3092ba3c
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/panicking.rs:92:14
>   15:     0x55745051c30d - core::panicking::panic::h3de4db67bd397eb3
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/panicking.rs:50:5
>   16:     0x557450847a8d - core::option::Option<T>::unwrap::hf95404a03dcdec27
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/option.rs:388:21
>   17:     0x5574505505be - <jrsonnet_cli::MiscOpts as clap::derive::FromArgMatches>::from_arg_matches::he5b374a4e6d116b3
>                                at /mnt/StorageArray0/Development/Local/jrsonnet/crates/jrsonnet-cli/src/lib.rs:48:13
>   18:     0x5574505507d9 - <jrsonnet_cli::GeneralOpts as clap::derive::FromArgMatches>::from_arg_matches::h2995351b89fa82a7
>                                at /mnt/StorageArray0/Development/Local/jrsonnet/crates/jrsonnet-cli/src/lib.rs:76:9
>   19:     0x557450522b3c - <jrsonnet::Opts as clap::derive::FromArgMatches>::from_arg_matches::h7c3532fa81d7424d
>                                at /mnt/StorageArray0/Development/Local/jrsonnet/cmds/jrsonnet/src/main.rs:57:9
>   20:     0x5574505265f7 - clap::derive::Clap::parse::h8a0c6a0b506304c0
>                                at /home/userd/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/src/derive.rs:77:9
>   21:     0x55745051f749 - jrsonnet::main::ha4593186b5a63a22
>                                at /mnt/StorageArray0/Development/Local/jrsonnet/cmds/jrsonnet/src/main.rs:68:19
>   22:     0x5574505276bb - core::ops::function::FnOnce::call_once::h5a5a17fc330bc772
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/ops/function.rs:227:5
>   23:     0x55745051e68e - std::sys_common::backtrace::__rust_begin_short_backtrace::h953e20ac34f306ce
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/sys_common/backtrace.rs:125:18
>   24:     0x55745051d601 - std::rt::lang_start::{{closure}}::ha22dadcb0fa00322
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/rt.rs:49:18
>   25:     0x5574508f8a49 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd933294140eb11aa
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/ops/function.rs:259:13
>   26:     0x5574508f8a49 - std::panicking::try::do_call::h8342fe3d9218b807
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:401:40
>   27:     0x5574508f8a49 - std::panicking::try::hcbd73d6d0d58a8f0
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:365:19
>   28:     0x5574508f8a49 - std::panic::catch_unwind::hde9cf73f810acfcc
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panic.rs:434:14
>   29:     0x5574508f8a49 - std::rt::lang_start_internal::heb39e7ea6e5d6f6f
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/rt.rs:34:21
>   30:     0x55745051d5e0 - std::rt::lang_start::hbb8edbeabd2afdfa
>                                at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/rt.rs:48:5
>   31:     0x557450522f2c - main
>   32:     0x7fba01e8db25 - __libc_start_main
>   33:     0x55745051cbbe - _start
>   34:                0x0 - <unknown>

The issue is not present with version 3.5.

Kind regards

**Comment by bruno-delfino1995** [comment]
Probably, because of the new clap version introduced by me. @CertainLach will [revert](https://github.com/CertainLach/jrsonnet/pull/44#issuecomment-855266761) it, and it'll be released as part of `0.3.8`.

**Comment by CertainLach** [comment]
Fixed in https://github.com/CertainLach/jrsonnet/releases/tag/v0.3.8
