### ISSUE TITLE
function evaluation unwrap error

### ISSUE THREAD

**Issue by jiangzhe** [CertainLach/jrsonnet#5]
```
function(config={})
{
  [if 1 == 1 then "item" + std.toString(x)]: x for x in std.range(0,2)
}
```
When evaluation above code, it panicked:

_thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/jrsonnet-evaluator/src/lib.rs:128:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace_

I tracked the call stacks and found it may be causd by stdlib missing.
Is there any reason that not importing the stdlib in function scope? I tried with go-jsonnet and it's fine.

**Comment by CertainLach** [comment]
In `jrsonnet` all evaluation state is stored in TLS, which being filled when it needed

There was missing state enter on TLA evaluation, fixed in 4accdd0afdc96071a6bf819c1e1ddc35ece3e78c, thanks!
