### ISSUE TITLE
Release 0.3.0 is missing the last commit

### ISSUE THREAD

**Issue by bruno-delfino1995** [CertainLach/jrsonnet#7]
The code from the [last commit](https://github.com/CertainLach/jrsonnet/commit/4accdd0afdc96071a6bf819c1e1ddc35ece3e78c) of [Release 0.3.0](https://github.com/CertainLach/jrsonnet/releases/tag/0.3.0) is not present on the package published at [crates.io](https://crates.io/crates/jrsonnet-evaluator).

I checked that it does exist within the zipped code. But when using `jrsonnet-evaluator = "0.3.0"` on my dependencies, I get [this code](https://docs.rs/jrsonnet-evaluator/0.3.0/src/jrsonnet_evaluator/lib.rs.html#332-341), which is different from what is under the tag [0.3.0](https://github.com/CertainLach/jrsonnet/tree/0.3.0).

From what I saw, the release workflow only publishes to GitHub release and not to crates.io. Could it have been a problem when manually publishing the crate?

**Comment by CertainLach** [comment]
Yep, crate is published manually, and i missed version bump for it

I will add crates.io publishing to release workflow now

**Comment by CertainLach** [comment]
Github action development is hard, i didn't found implementation of action for `cargo-release`, so i tried to write my own
There is no place to store state, so it's seems to be impossible

So, i will bumped version manually to `0.3.1` in 23c027a07375b1ee5b76ecb7f5adf5f9637397f8
