### ISSUE TITLE
Recommendations for server-side evaluation of untrusted Jsonnet?

### ISSUE THREAD

**Issue by emschwartz** [CertainLach/jrsonnet#71]
Thanks so much for creating this library!

The Jsonnet website has a [warning about server-side Jsonnet evaluation](https://jsonnet.org/ref/bindings.html).

**Is there a safe way to evaluate untrusted Jsonnet using `jrsonnet` on the server-side?** For example, by limiting the max stack size, the size of the inputs, etc. Are there any other settings / considerations you would recommend for this setup?

In a similar vein, the jrsonnet CLI implementation [spawns a separate thread](https://github.com/CertainLach/jrsonnet/blob/master/cmds/jrsonnet/src/main.rs#L88-L99) to run the evaluator. I'm assuming one would want to do the same on the server side, but probably use a thread pool and ensure that panics in the various threads are not propagated to the API handling the requests. Would you agree with that approach?

**Comment by CertainLach** [comment]
Currently there is no way to prevent infinite loops/memory exhaustion/other, so it is not generally safe to use this library for handling arbitary user input
Best you can do now is to build jrsonnet as wasm, and limit memory for wasm virtual machine (There still be possible infinite loops, but i don't see way to cause them), or (better) spawn different process for jsonnet evaluation (Startup overhead is negilible, you shouldn't need process pool in most cases, i think)

As for jrsonnet CLI - separate thread is created with increased stack size, as by default it isn't sufficient for some benchmarks (I saw no jrsonnet library, which exceeds default thread stack size)

I may provide some more options if i knew your usecase, btw

**Comment by emschwartz** [comment]
Thanks for the suggestions!

My use case involves having a product-specific template library like [grafonnet](https://github.com/grafana/grafonnet-lib) that generates and submits JSON objects to a REST API (technically it's not submitting them via HTTP but to the same handler that would handle the HTTP request). I need to be able to fill out a template based on the contents of a webhook.

For now, I think I'll go with spawning separate processes to evaluate the Jsonnet code and use cgroups/ulimit to limit the CPU and memory of the child process.
