### ISSUE TITLE
Help extracting details of an exported function parameter

### ISSUE THREAD

**Issue by emschwartz** [CertainLach/jrsonnet#79]
I have a use case where I want to determine the details (name, type, and default value) of an exported Jsonnet function. My current approach works for parameters with default values that are plain value expressions (`function (a=1, b="two", c=null)`) but fails when the default value references a value or function defined elsewhere in the file:

```rust
        if let Val::Func(func) = exported_value {
            if let FuncVal::Normal(func) = func.as_ref() {
                for param in func.params.iter() {
                    if let Some(expr) = &param.1 {
                        let val = state
                            .evaluate_expr_raw(expr.clone())
```
Is there a better way to evaluate a `LocExpr` in the global context to determine what the value it produces will be?

Thanks for your help!

**Comment by CertainLach** [comment]
There is no such functionality built-in, but this should be possible to implement by restructuring AST to only include expressions needed for this parameter

However, there is breakpoint functionality built-in in `gcmodule` branch, which allows to examine values by its locations, and it may be suitable in your case?

**Comment by emschwartz** [comment]
Thanks for the quick response!

This is very much at the limit of my understanding of programming language implementations so I'm not entirely sure what that would entail.

Just for clarification: why wouldn't it work to simply evaluate the parameter expression in the `EvaluationState` context? I'm evaluating the jsonnet file with `evaluate_snippet_raw`, then checking if the returned value is a function and, if so, inspecting its parameters. I would think that simply evaluating the parameters would be enough to determine what values they produce, but maybe I'm misunderstanding either Jsonnet (for example, the implications of lazy evaluation) or this library.

**Comment by CertainLach** [comment]
As i understood your question, you want to know default value of `x` in this expression:
```jsonnet
local v = 1;
local d = function(x = v) 1;
d(2)
```

And to evaluate it, we should know value of `v` in parent context
Because `jsonnet` is normally evaluated in direct order, existing code can't be used in this case, jsonnet can't walk expression tree up to `v`, and then evaluate its value, it should first evaluate `local`, and then function argument

In these cases you should either build your own static analyzer, which allows bottom-top execution of jsonnet, or restructure jsonnet to something like

```jsonnet
local v = 1;
v
```
And then use existing evaluator

However, this is harder in other cases, i.e 
```jsonnet
{
  v: 1,
  k(x = $.v) x
}
```

And impossible in cases like
```jsonnet
local
a = std.extVar("a"),
b = std.extVar("b");
{
  [a]: function(x = $[b]) x,
  'x': 4,
}
```

**Comment by CertainLach** [comment]
Oh, your case is simplier
> then checking if the returned value is a function

In your case you already got FuncVal, so you can get context from it, and then evaluate arguments using it, yes
https://github.com/CertainLach/jrsonnet/blob/e1fb5e1edb6f4935484bb3073564c8808e7fafac/crates/jrsonnet-evaluator/src/val.rs#L85

I may write this helper method for you, as i will need something like this for myself soon

**Comment by emschwartz** [comment]
Yeah, sorry I should have provided an example.

I'm given a jsonnet file that returns a function (that will take some top-level arguments) and I want to know what the top level arguments should be.

For example:
```jsonnet
local num = 1;
local str = "two";
function(a=num, b=str) {}
```

I'd like to know that this exports a function that takes two TLAs: `a`, which defaults to the number `1`, and `b`, which defaults to the string `"two"`.

**Comment by CertainLach** [comment]
Naive solution would be
```rust
	fn function_args_naive() -> Result<(), LocError> {
		let es = EvaluationState::default();
		let path = PathBuf::from("input.jsonnet");
		let func = es
			.evaluate_snippet_raw(
				path.into(),
				r#"
					local num = 1;
					local str = "two";
					function(a=num, b=str) {}
				"#
				.into(),
			)?
			.as_func()
			.unwrap();
		let func = match func {
			FuncVal::Normal(f) => f,
			_ => unreachable!(),
		};

		for param in func.params.iter() {
			print!("{}", param.0);
			if let Some(v) = &param.1 {
				let v = es.run_in_state(|| evaluate(func.ctx.clone(), v))?;
				print!(" = {}", v.manifest(&ManifestFormat::Json(3))?);
			}
			println!(",");
		}

		Ok(())
	}
```

Output is
```
a = 1,
b = "two",
```

However, this code wouldn't work in case if argument is depends on other
```jsonnet
function(a, b = a) // Will fail, as a would be undefined
```

In this case much complex code is required:

```rust
	fn function_args_full() -> Result<(), LocError> {
		let es = EvaluationState::default();
		let path = PathBuf::from("input.jsonnet");
		let func = es
			.evaluate_snippet_raw(
				path.into(),
				r#"
					local num = 1;
					local str = "two";
					function(a=num, b=str, c = b, d, e = d) {}
				"#
				.into(),
			)?
			.as_func()
			.unwrap();
		let func = match func {
			FuncVal::Normal(f) => f,
			_ => unreachable!(),
		};

		let ctx = Context::new_future();

		let mut bindings = GcHashMap::new();

		#[derive(Trace)]
		struct DependsOnUnbound(IStr);
		impl LazyValValue for DependsOnUnbound {
			fn get(self: Box<Self>) -> Result<Val> {
				Err(
					RuntimeError(format!("dependence on unbound argument {}", self.0).into())
						.into(),
				)
			}
		}
		#[derive(Trace)]
		struct EvaluateArgument(LocExpr, FutureWrapper<Context>);
		impl LazyValValue for EvaluateArgument {
			fn get(self: Box<Self>) -> Result<Val> {
				evaluate(self.1.unwrap(), &self.0)
			}
		}

		for param in func.params.iter() {
			if let Some(v) = &param.1 {
				bindings.insert(
					param.0.clone(),
					LazyVal::new(TraceBox(Box::new(EvaluateArgument(v.clone(), ctx.clone())))),
				);
			} else {
				bindings.insert(
					param.0.clone(),
					LazyVal::new(TraceBox(Box::new(DependsOnUnbound(param.0.clone())))),
				);
			}
		}

		let ctx = func.ctx.clone().extend_bound(bindings).into_future(ctx);

		for param in func.params.iter() {
			print!("{}", param.0);
			if param.1.is_some() {
				let result = es.run_in_state(|| -> Result<IStr> {
					let binding = ctx.binding(param.0.clone())?;
					let value = binding.evaluate()?;
					Ok(value.manifest(&ManifestFormat::Json(3))?)
				});
				match result {
					Ok(v) => print!(" = {}", v),
					Err(e) => print!(": error({})", e.error().to_string()),
				}
			}
			println!(",")
		}

		Ok(())
	}
```

Output is 

```
a = 1,
b = "two",
c = "two",
d,
e: error(runtime error: dependence on unbound argument d),
```

**Comment by emschwartz** [comment]
Amazing, thank you! I'll go with the naive solution for now, as I'm okay not supporting this for params that depend on one another, but it's good to know that that requires a more fully-fledged solution.

**Comment by CertainLach** [comment]
Added helper method which implements second approach: https://github.com/CertainLach/jrsonnet/commit/c7fb88801c20f00b5114f38231a5b76df0429e7c

Native solution is also broken when there is both argument and local with same name in context, i.e:

```jsonnet
local a = 1;
function(a = 2, b = a) {} // b would be detected as 1, but it should be 2
```
