### ISSUE TITLE
`--exec` should stringify output, instead of manifestification

### ISSUE THREAD

**Issue by kppullin** [CertainLach/jrsonnet#8]
This is really minor and as far as I can tell not part of the spec, however wanted to note that empty objects are emitted without a space between the braces (`{}`), which is different (`{ }`) compared to both the C++ and go jsonnet versions as well as sjsonnet.

Examples:

```
❯ jsonnet -e '{ }'
{ }
```

```
❯ jrsonnet -e '{ }'
{}
```

Thanks for the effort on this project!  My anecdotal benchmarking against a slightly modified `kube-prometheus` configuration runs in ~500ms vs sjsonnet @ ~3s, jsonnet (go) @ ~15s, and jsonnet (C++) @ 120s.  Coming from the C++ version (I wasn't aware of the go port and sjsonnet failed last time I tried it), this ran so fast that I thought it must surely be broken!

**Comment by CertainLach** [comment]
Oh, i see

Both go and c++ versions have a `-e` flag perform a `std.toString` on result, while i have manifest output (as with standard jsonnet outputting files), as for the file input
