### ISSUE TITLE
Add release binaries for darwin-arm64

### ISSUE THREAD

**Issue by fcvarela** [CertainLach/jrsonnet#80]
Is there any chance this could be added? Thanks.

**Comment by bruno-delfino1995** [comment]
@CertainLach, I'll tackle this one! I just did a [test](https://github.com/bruno-delfino1995/jrsonnet/actions/runs/2266970839), and it seemed to work. @fcvarela, can you please download the artifact and check whether everything runs fine?

I don't have an M1 Mac, not even a normal Mac, so I'm not sure whether the binaries are working. Once I receive an OK from you, I'll update the pipelines with the new binary.

**Comment by fcvarela** [comment]
@CertainLach Works fine, many thanks!

**Comment by CertainLach** [comment]
I have integrated darwin-aarch64 builds in latest release:
https://github.com/CertainLach/jrsonnet/releases/tag/v0.5.0-pre3-test

**Comment by m-messiah** [comment]
@CertainLach could you please backport it to 0.4.2 and add the asset there? It looks like 0.5.0 won't be soon..
