### ISSUE TITLE
bug(cli): command completion generation requires `<INPUT>` parameter

### ISSUE THREAD

**Issue by JarvisCraft** [CertainLach/jrsonnet#81]
# Description

Generating Clippy's tab-completions support requires the dummu `<INPUT>` parameter to be present.

## Steps to reproduce

1. Run

```shell
$ jrsonnet generate bash
```

`bash` can be replaced with any supported shell.

### Expected behaviour

Tab-completion code is generated for the provided shell.

### Observed behaviour

```shell
error: The following required arguments were not provided:
    <INPUT>

USAGE:
    jrsonnet [OPTIONS] <INPUT> [SUBCOMMAND]

For more information try --help
```

Tab-completion code is geneated only in presence of (any) `<INPUT>` parammeter value.

**Comment by CertainLach** [comment]
Unfortunately, it seems to be still not possible to implement correctly with current clap api

**Comment by CertainLach** [comment]
Actually, found workaround.
