### ISSUE TITLE
'-' for stdin

### ISSUE THREAD

**Issue by rrichardson** [CertainLach/jrsonnet#9]
I would like to dynamically generate and pass my root jsonnet in via stdin.   
e.g. 

```
collect_files.sh | jrsonnet -
```

`-` is pretty universally accepted as a hint to the process to read its primary file from stdin instead of a file path.  
FWIW, The C++ jsonnet app supports this.

**Comment by CertainLach** [comment]
Didn't knew vanilla jsonnet accepts input from stdin

As a workaround, you can use `collect_files.sh | jrsonnet /dev/stdin` currently

**Comment by rrichardson** [comment]
That's a handy tip.  Thanks.
