### ISSUE TITLE
cargo install?

### ISSUE THREAD

**Issue by AlJohri** [CertainLach/jrsonnet#96]
is it possible to `cargo install` the jrsonnet CLI? If not, would it be possible to support this mode of installation?

I see the [jrsonnet crate](https://crates.io/crates/jrsonnet) was yanked from crates.io. I also didn't see the [jrsonnet-cli](https://crates.io/crates/jrsonnet-cli) published on crates.io.

**Comment by CertainLach** [comment]
It is possible, using git dependency:
```
cargo install --git https://github.com/CertainLach/jrsonnet
```

**Comment by AlJohri** [comment]
great, that worked! any reason to not publish to crates.io?

**Comment by CertainLach** [comment]
I wanted to release new version of jrsonnet in december, but I was busy, and haven't managed to deliver final strokes.

For now, I have published prerelease (To at least reserve package names), you can install it using
```
cargo install jrsonnet --version 0.5.0-pre6
```

`jrsonnet-cli` package is not a `jrsonnet` command, but the definition of its arguments for clap command line argument parsing library, which may be used for other utilities.

**Comment by AlJohri** [comment]
Great, thanks for the clarification! Closing as complete :)
