### ISSUE TITLE
gcmodule: assertion failed: `(left == right)` left: `44`, right: `48` on 32-bit platforms

### ISSUE THREAD

**Issue by messense** [CertainLach/jrsonnet#97]
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `44`,
 right: `48`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jrsonnet-gcmodule-0.3.4/src/cc.rs:180:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/CertainLach/gcmodule/blob/91ce25395b630a54d1c3c6ccd620d9bc9ca9b069/src/cc.rs#L180-L183

**Comment by messense** [comment]
In release mode, this or something else causes segfault.

**Comment by CertainLach** [comment]
That's interesting, seems like rustc decided to use some weird alignment on Gc structure

I can't reproduce this issue on either i686-unknown-linux-gnu nor i686-pc-windows-gnu using jrsonnet own test suite (`cargo test --workspace`)
Can you please provide me more context? File, on which jrsonnet fails, or maybe reproducing code?

I think specifying alignment on RawCcBoxWithGcHeader may help:
```diff
- #[repr(C)]
+ #[repr(C, align(4))]
  pub struct RawCcBoxWithGcHeader<T: ?Sized, O: AbstractObjectSpace> {
```

**Comment by messense** [comment]
> I think specifying alignment on RawCcBoxWithGcHeader may help:

https://github.com/messense/gcmodule/commit/622f6665dd7fc20d9ec75cd76bbed5a9bd67a1cc

Doesn't seem to work? https://github.com/messense/rjsonnet-py/actions/runs/3966464324/jobs/6797293150#step:5:97


> Can you please provide me more context? File, on which jrsonnet fails, or maybe reproducing code?

I'm trying to get a meaningful stack trace, no luck yet.

**Comment by CertainLach** [comment]
Can you try with jrsonnet-align branch of gcmodule?
I still haven't reproduced this issue, but I'm pretty sure this branch should make it work for now.

**Comment by CertainLach** [comment]
This branch implements fix in a not very pretty way, by forcing alignment of 8 on header/value on x32 (header should be enough), but it isn't possible to implement correct fix yet, not with the current GC implementation.

**Comment by messense** [comment]
Thanks! I've verified that most of them are fixed, there is another assertion failure on Windows x86, opened https://github.com/CertainLach/jrsonnet/issues/98.
