### ISSUE TITLE
Manifesting a yaml tag

### ISSUE THREAD

**Issue by Jezza** [CertainLach/jrsonnet#99]
YAML has support for tags like:
```yaml
includes:
- !include components/accounts.yaml
```

That `!include` is a directive that the code the uses to invoke some code-side constructor.
Weird, but it's supported. (yml in a nutshell)  

When the yml document is manifested, the string is checked to see if it starts with a `!`, if it does, then it quotes the string.

I'm wondering if there's a workaround for this, or if we could change this.

**Comment by CertainLach** [comment]
Tags are not intended to be produced by serializer, and deserializer is free to drop tags, if it doesn't have special handling for them, thus this does break roundtrip, as
```jsonnet
std.manifestYamlDoc(std.parseYaml("a: !tag world")) == '"a": "world"'
```

If you really need to produce directive - you can write your own manifestYamlDoc, by copying the default implementation

But in your case, why not just process includes on jsonnet side?
```jsonnet
{
  includes: [
    std.parseYaml(importstr 'components/accounts.yaml'),
    // Or rewrite accounts.yaml to jsonnet, and then
    import 'components/accounts.jsonnet',
  ],
}
```

In any case, this thing should not be discussed here, but in jsonnet issue tracker: https://github.com/google/jsonnet/issues

**Comment by Jezza** [comment]
For includes, I just end up dropping them, and writing the content directly.  
That's fine, but there's a couple that cause issue.  
I'll find some workarounds.  

Thanks for your time!
